import type { PatternResult } from './types';
import { renderPattern, renderPreview } from './patternRenderer';
import { getBrand } from './paletteData';

/**
 * Export the pattern as a PNG image.
 */
export function exportPng(pattern: PatternResult, title?: string): void {
  const canvas = renderPattern(pattern, {
    cellSize: 24,
    showGrid: true,
    showCoordinates: true,
    showBoardLines: true,
    showLegend: true,
    title: title || `Bead Pattern — ${pattern.width}×${pattern.height}`
  });

  canvas.toBlob((blob) => {
    if (!blob) return;
    downloadBlob(blob, sanitizeFilename(title || `bead_pattern_${pattern.width}x${pattern.height}`) + '.png');
  }, 'image/png');
}

/**
 * Export the pattern as a JPEG image.
 */
export function exportJpeg(pattern: PatternResult, title?: string): void {
  const canvas = renderPattern(pattern, {
    cellSize: 24,
    showGrid: true,
    showCoordinates: true,
    showBoardLines: true,
    showLegend: true,
    title: title || `Bead Pattern — ${pattern.width}×${pattern.height}`
  });

  canvas.toBlob((blob) => {
    if (!blob) return;
    downloadBlob(blob, sanitizeFilename(title || `bead_pattern_${pattern.width}x${pattern.height}`) + '.jpg');
  }, 'image/jpeg', 0.92);
}

/**
 * Export a small preview image (for sharing / thumbnails).
 */
export function exportPreviewImage(pattern: PatternResult): void {
  const canvas = renderPreview(pattern, 600);
  canvas.toBlob((blob) => {
    if (!blob) return;
    downloadBlob(blob, `bead_preview_${pattern.width}x${pattern.height}.png`);
  }, 'image/png');
}

/**
 * Open the browser print dialog with a print-optimized layout.
 * The user can then save as PDF from the print dialog.
 */
export function exportPrint(pattern: PatternResult, title?: string): void {
  const canvas = renderPattern(pattern, {
    cellSize: 18,
    showGrid: true,
    showCoordinates: true,
    showBoardLines: true,
    showLegend: true,
    title: title || `Bead Pattern — ${pattern.width}×${pattern.height}`
  });

  const dataUrl = canvas.toDataURL('image/png');
  const brand = getBrand(pattern.brandId);

  const printHtml = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>${title || 'Bead Pattern'}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: "Inter", "Segoe UI", "Microsoft YaHei", sans-serif;
    color: #18202e;
    background: #fff;
    padding: 20px;
  }
  .header { margin-bottom: 16px; }
  .header h1 { font-size: 20px; font-weight: 700; }
  .header p { font-size: 12px; color: #5d6b81; margin-top: 4px; }
  .pattern-img {
    max-width: 100%;
    height: auto;
    image-rendering: pixelated;
  }
  .materials-table {
    margin-top: 20px;
    width: 100%;
    border-collapse: collapse;
    font-size: 11px;
  }
  .materials-table th {
    text-align: left;
    padding: 6px 8px;
    border-bottom: 2px solid #e2e7f0;
    font-weight: 700;
    font-size: 10px;
    text-transform: uppercase;
    color: #5d6b81;
  }
  .materials-table td {
    padding: 4px 8px;
    border-bottom: 1px solid #f0f0f0;
  }
  .swatch {
    display: inline-block;
    width: 12px;
    height: 12px;
    border-radius: 2px;
    border: 1px solid #d0d0d0;
    vertical-align: middle;
    margin-right: 6px;
  }
  .footer {
    margin-top: 16px;
    font-size: 10px;
    color: #9e9e9e;
    text-align: center;
  }
  @page {
    size: A4 landscape;
    margin: 10mm;
  }
  @media print {
    body { padding: 0; }
  }
</style>
</head>
<body>
  <div class="header">
    <h1>${title || 'Bead Pattern'}</h1>
    <p>${pattern.width}×${pattern.height} · ${pattern.totalBeads} beads · ${pattern.materials.length} colors · ${brand.name} · Board size: ${pattern.boardSize}×${pattern.boardSize}</p>
  </div>
  <img class="pattern-img" src="${dataUrl}" alt="Bead pattern" />
  <table class="materials-table">
    <thead>
      <tr>
        <th></th>
        <th>Symbol</th>
        <th>Code</th>
        <th>Color Name</th>
        <th style="text-align:right">Count</th>
        <th style="text-align:right">%</th>
      </tr>
    </thead>
    <tbody>
      ${pattern.materials.map((m) => `
        <tr>
          <td><span class="swatch" style="background:${m.bead.hex}"></span></td>
          <td style="font-family:monospace">${m.symbol}</td>
          <td>${m.bead.code}</td>
          <td>${m.bead.name}</td>
          <td style="text-align:right;font-family:monospace">${m.count}</td>
          <td style="text-align:right;font-family:monospace">${m.percentage.toFixed(1)}%</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
  <div class="footer">
    Generated by Dot Matrix Studio · ${new Date().toLocaleDateString()}
  </div>
</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(printHtml);
    printWindow.document.close();
    // Wait for image to load before triggering print
    const img = printWindow.document.querySelector('img') as HTMLImageElement | null;
    if (img) {
      img.onload = () => printWindow.print();
    } else {
      printWindow.print();
    }
  }
}

/**
 * Export the materials list as CSV.
 */
export function exportCsv(pattern: PatternResult, title?: string): void {
  const brand = getBrand(pattern.brandId);
  const rows = [
    ['Symbol', 'Code', 'Color Name', 'Hex', 'Count', 'Percentage', 'Brand'].join(','),
    ...pattern.materials.map((m) =>
      [
        m.symbol,
        m.bead.code,
        `"${m.bead.name}"`,
        m.bead.hex,
        m.count,
        m.percentage.toFixed(1) + '%',
        brand.name
      ].join(',')
    )
  ];
  rows.push('');
  rows.push(`"Total",,,,${pattern.totalBeads},,"${pattern.width}×${pattern.height}"`);

  const content = rows.join('\n');
  const blob = new Blob(['﻿' + content], { type: 'text/csv;charset=utf-8' });
  downloadBlob(blob, sanitizeFilename(title || `bead_materials_${pattern.width}x${pattern.height}`) + '.csv');
}

/**
 * Export the full pattern data as JSON.
 */
export function exportJson(pattern: PatternResult, title?: string): void {
  const data = {
    title: title || '',
    width: pattern.width,
    height: pattern.height,
    brand: pattern.brandId,
    boardSize: pattern.boardSize,
    totalBeads: pattern.totalBeads,
    materials: pattern.materials.map((m) => ({
      symbol: m.symbol,
      code: m.bead.code,
      name: m.bead.name,
      hex: m.bead.hex,
      count: m.count,
      percentage: +m.percentage.toFixed(1)
    })),
    grid: pattern.cells.map((row) =>
      row.map((cell) => cell?.bead?.code ?? null)
    )
  };

  const content = JSON.stringify(data, null, 2);
  const blob = new Blob([content], { type: 'application/json;charset=utf-8' });
  downloadBlob(blob, sanitizeFilename(title || `bead_pattern_${pattern.width}x${pattern.height}`) + '.json');
}

// ── Helpers ──

function downloadBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function sanitizeFilename(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\-一-鿿]/g, '_').replace(/_+/g, '_');
}
