const base = {
  resizeMode: 'contain',
  backgroundColor: '#000000',
  transparentMode: 'blendBackground',
  threshold: 128,
  dithering: 'none',
  primaryDirection: 'forward',
  secondaryDirection: 'forward',
  origin: 'top-left',
  rotation: 0,
  flipX: false,
  flipY: false,
  outputFormat: 'c-array',
}

export const moduloPresets = [
  {
    ...base,
    id: 'wisdom-ili9341-bgr565',
    label: '智慧生活 V3.0 / ILI9341 BGR565',
    group: '智慧生活',
    width: 240,
    height: 240,
    colorFormat: 'BGR565',
    byteOrder: 'big',
    scanLayout: 'column',
  },
  {
    ...base,
    id: 'wisdom-ili9341-rgb565',
    label: '智慧生活 V3.0 / ILI9341 RGB565',
    group: '智慧生活',
    width: 240,
    height: 240,
    colorFormat: 'RGB565',
    byteOrder: 'big',
    scanLayout: 'column',
  },
  {
    ...base,
    id: 'pctolcd2002-16x16-mono',
    label: 'PCtoLCD2002 16x16 单色字模',
    group: 'PCtoLCD2002',
    width: 16,
    height: 16,
    colorFormat: 'MONO1',
    monoPolarity: 'yin',
    bitOrder: 'msb',
    scanLayout: 'row',
  },
  {
    ...base,
    id: 'pctolcd2002-32x32-mono',
    label: 'PCtoLCD2002 32x32 单色字模',
    group: 'PCtoLCD2002',
    width: 32,
    height: 32,
    colorFormat: 'MONO1',
    monoPolarity: 'yin',
    bitOrder: 'msb',
    scanLayout: 'row',
  },
  {
    ...base,
    id: 'lvgl-rgb565',
    label: 'LVGL RGB565',
    group: 'LVGL',
    width: 240,
    height: 240,
    colorFormat: 'RGB565',
    byteOrder: 'big',
    scanLayout: 'row',
    outputFormat: 'lvgl',
  },
  {
    ...base,
    id: 'lvgl-rgb888',
    label: 'LVGL RGB888',
    group: 'LVGL',
    width: 240,
    height: 240,
    colorFormat: 'RGB888',
    scanLayout: 'row',
    outputFormat: 'lvgl',
  },
  {
    ...base,
    id: 'lvgl-argb8888',
    label: 'LVGL ARGB8888',
    group: 'LVGL',
    width: 240,
    height: 240,
    colorFormat: 'ARGB8888',
    scanLayout: 'row',
    outputFormat: 'lvgl',
  },
  {
    ...base,
    id: 'arduino-tft-rgb565',
    label: 'Arduino TFT RGB565 PROGMEM',
    group: 'Arduino',
    width: 240,
    height: 240,
    colorFormat: 'RGB565',
    byteOrder: 'big',
    scanLayout: 'row',
    outputFormat: 'arduino',
  },
  {
    ...base,
    id: 'oled-128x64-row',
    label: '通用 OLED 128x64 横向字节',
    group: 'OLED',
    width: 128,
    height: 64,
    colorFormat: 'MONO1',
    monoPolarity: 'yin',
    bitOrder: 'msb',
    scanLayout: 'row',
  },
  {
    ...base,
    id: 'oled-128x64-page',
    label: 'SSD1306 OLED 128x64 页模式',
    group: 'OLED',
    width: 128,
    height: 64,
    colorFormat: 'MONO1',
    monoPolarity: 'yin',
    bitOrder: 'msb',
    scanLayout: 'page',
  },
]

export const listPresets = () => moduloPresets.map(preset => ({ ...preset }))

export const getPreset = (id) => {
  const preset = moduloPresets.find(item => item.id === id)
  if (!preset) throw new Error(`Unknown modulo preset: ${id}`)
  return { ...preset }
}

